name: Deploy para Produção

on:
  push:
    branches:
      - main  # dispara o deploy ao dar push na main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3

      - name: Deploy via SSH na VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: "46.202.144.162"
          username: "root"
          key: ${{ secrets.VPS_SSH_KEY }}
      
          script: |
            cd /root/code/app-deploy/DiaDosNamorados/myapp
            git pull origin main
            npm install
            nohup npm start > /dev/null 2>&1 &
            cd ../Amores
            npm install
            nohup npm run dev -- --host > /dev/null 2>&1 &
            exit 0

            


           
